from networksecurity.entity.config_entity import DataIngestionConfig,TraingPipelineConfig,DataValidationConfig
from networksecurity.entity.atifact_entity import DataIngetionArtifact,DataValidationArtifact,DataTransformationArtifact
from networksecurity.utils.read_write import read_yaml,write_yaml,save_numpy_array,save_object_pkl
import os 
import sys
from networksecurity.logging.logging import logging
from networksecurity.exception.exception import CustomException
from networksecurity.constants.trainig_pipeline import TARGET_COLUMN,DATA_TRANSFORMATION_IMPUTER_PARAMS

import pandas as pd

from sklearn.impute import KNNImputer
from sklearn.pipeline import Pipeline
